### PR TITLE
chore: added statement timeout gem

### PR DESCRIPTION
**Pull request by mehulmathur16**
/claim #880

### CODE REVIEW

**Comment by ezekg** [comment]
CI will likely fail since our CI requires secrets and GH doesn't like to allow secrets to third-party PRs.

Will run CI locally regardless. ty 👍

**Comment by ezekg** [comment]
Can you resolve the conflicts?

**Comment by mehulmathur16** [comment]
done

**Comment by ezekg** [comment]
Please squash commits. ty

**Comment by ezekg** [comment]
Still seeing conflicts. 🙂

**Pull request merged**
